server.port: 8080

spring:
  application.name: api-gateway
  main.allow-bean-definition-overriding: true
  security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8181/realms/microshop
  cloud.gateway.mvc:
    routes:
    - id: product-service
      uri: lb://product-service
      predicates:
      - Path=/api/product
    - id: order-service
      uri: lb://order-service
      predicates:
      - Path=/api/order
    - id: inventory-service
      uri: lb://inventory-service
      predicates:
      - Path=/api/inventory
    - id: discovery-server
      uri: http://localhost:8761
      predicates:
        - Path=/eureka/web
      filters:
        - SetPath=/
    - id: discovery-server-static
      uri: http://localhost:8761
      predicates:
        - Path=/eureka/**

management:
  endpoints.web.exposure.include: health, info, metrics, prometheus
  metrics.distribution.percentiles-histogram.http.server.requests: true
  observations.key-values.application: api-gateway
  tracing.sampling.probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

logging.level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE
