server.port: 0

spring:
    application.name: order-service
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/order-service
        username: postgres
        password: postgres
    jpa:
        hibernate.ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

management:
  health.circuitbreakers.enable: true
  endpoints:
    web.exposure.include: *
    health.show-details: always

resilience4j:
  circuitbreaker.instances.inventory:
    registerHealthIndicator: true
    event-consumer-buffer-size: 10
    slidingWindowType: COUNT_BASED
    slidingWindowSize: 5
    failureRateThreshold: 50
    waitDurationInOpenState: 5s
    permittedNumberOfCallsInHalfOpenState: 3
    automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter.instances.inventory:
    timeout-duration: 3s
  retry.instances.inventory:
    max-attempts: 3
    wait-duration: 5s