global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]
  - job_name: 'eureka'
    eureka_sd_configs:
      - server: http://eureka:password@host.docker.internal:8761/eureka
    metrics_path: '/actuator/prometheus'
    relabel_configs:
      # Replace 'localhost' with 'host.docker.internal' in target address
      - source_labels: [ __address__ ]
        regex: '(localhost)(:.*)'
        replacement: 'host.docker.internal${2}'
        target_label: __address__