server.port: 8761

eureka:
  username: ${EUREKA_USERNAME:eureka}
  password: ${EUREKA_PASSWORD:password}
  instance.hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false

management:
  endpoints.web.exposure.include: health, info, metrics, prometheus
  metrics.distribution.percentiles-histogram.http.server.requests: true
  observations.key-values.application: discovery-service
  tracing.sampling.probability: 1.0
