server.port: 0

spring:
    application.name: product-service
    data.mongodb.uri: mongodb://localhost:27017/product-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

management:
  endpoints.web.exposure.include: health, info, metrics, prometheus
  metrics.distribution.percentiles-histogram.http.server.requests: true
  observations.key-values.application: product-service
  tracing.sampling.probability: 1.0
