server.port: 0

spring:
  application.name: inventory-service
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5433/inventory-service
      username: postgres
      password: postgres
  jpa:
      hibernate.ddl-auto: update

management:
  tracing.sampling.probability: 1.0
  zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
